# Generated by Django 3.1.5 on 2021-02-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
