# Generated by Django 3.1.5 on 2021-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
