# Generated by Django 3.1.5 on 2021-02-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilities',
            old_name='facillity',
            new_name='facility',
        ),
    ]
