# Generated by Django 3.1.5 on 2021-02-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='userDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdata'),
        ),
    ]
