# Generated by Django 3.1.5 on 2021-02-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_turf_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='gallery',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='turf',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
