# Generated by Django 3.1.5 on 2021-02-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210205_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='amount',
        ),
    ]
