# Generated by Django 3.1.5 on 2021-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_turf_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='facilities',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
