# Generated by Django 3.1.5 on 2021-02-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210205_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
