# Generated by Django 3.1.5 on 2021-02-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210206_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
