# Generated by Django 3.1.5 on 2021-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210206_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('football', models.CharField(blank=True, max_length=100, null=True)),
                ('cricket', models.CharField(blank=True, max_length=100, null=True)),
                ('badminton', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
    ]
