# Generated by Django 3.1.5 on 2021-02-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210208_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
