# Generated by Django 3.1.5 on 2021-02-09 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_category_icon'),
        ('user', '0019_auto_20210209_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='price',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='review',
        ),
        migrations.CreateModel(
            name='turfFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.facilities')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.turf')),
            ],
        ),
        migrations.CreateModel(
            name='sportPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.category')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.turf')),
            ],
        ),
    ]
