# Generated by Django 3.1.5 on 2021-02-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210209_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
