# Generated by Django 3.1.5 on 2021-02-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_turf_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_period',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='turf_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='userdata',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.sportprice'),
        ),
    ]
