# Generated by Django 3.1.5 on 2021-02-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20210211_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='sport',
            new_name='category',
        ),
    ]
