# Generated by Django 3.1.5 on 2021-02-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20210211_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='category',
            new_name='sport',
        ),
    ]
