# Generated by Django 3.1.5 on 2021-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20210211_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
