# Generated by Django 3.1.5 on 2021-02-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
