# Generated by Django 3.1.5 on 2021-02-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='users',
        ),
    ]
