# Generated by Django 3.1.5 on 2021-02-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20210212_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='users',
            new_name='user',
        ),
    ]
