# Generated by Django 3.1.5 on 2021-02-15 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0006_delete_vendorturf'),
        ('user', '0036_auto_20210213_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='sport',
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
