# Generated by Django 3.1.5 on 2021-02-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20210215_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='exists',
            field=models.BooleanField(default=False),
        ),
    ]
