# Generated by Django 3.1.5 on 2021-02-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_booking_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='exists',
            field=models.CharField(blank=True, default='not', max_length=20, null=True),
        ),
    ]
