# Generated by Django 3.1.5 on 2021-02-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20210215_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='exists',
            field=models.BooleanField(default=False),
        ),
    ]
