# Generated by Django 3.1.5 on 2021-02-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_userdata_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
