# Generated by Django 3.1.5 on 2021-02-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20210226_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
