# Generated by Django 3.1.5 on 2021-02-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_auto_20210226_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='turf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.turf'),
        ),
    ]
