# Generated by Django 3.1.5 on 2021-02-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20210226_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdata'),
        ),
    ]
