# Generated by Django 3.1.5 on 2021-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_comment_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ttpe_of_booking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
