# Generated by Django 3.1.5 on 2021-02-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_20210227_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userdata'),
        ),
    ]
