# Generated by Django 3.1.5 on 2021-03-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_booking_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(blank=True, max_length=20, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=20, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.turf')),
            ],
        ),
    ]
