# Generated by Django 3.1.5 on 2021-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
