# Generated by Django 3.1.5 on 2021-03-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_coupon_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(blank=True, default='default', max_length=20, null=True),
        ),
    ]
