# Generated by Django 3.1.5 on 2021-03-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_coupon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
