# Generated by Django 3.1.5 on 2021-03-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_auto_20210304_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='hey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
