# Generated by Django 3.1.5 on 2021-03-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_coupon_hey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='hey',
        ),
    ]
