# Generated by Django 3.1.5 on 2021-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_remove_coupon_hey'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='game',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
